/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminRevenueRouteImport } from './routes/_authenticated/admin.revenue'
import { Route as AuthenticatedAdminNewRouteImport } from './routes/_authenticated/admin.new'
import { Route as AuthenticatedAdminListingsRouteImport } from './routes/_authenticated/admin.listings'
import { Route as AuthenticatedAdminGeneratorRouteImport } from './routes/_authenticated/admin.generator'
import { Route as AuthenticatedAdminEditIdRouteImport } from './routes/_authenticated/admin.edit.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRevenueRoute =
  AuthenticatedAdminRevenueRouteImport.update({
    id: '/revenue',
    path: '/revenue',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewRoute = AuthenticatedAdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminListingsRoute =
  AuthenticatedAdminListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGeneratorRoute =
  AuthenticatedAdminGeneratorRouteImport.update({
    id: '/generator',
    path: '/generator',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEditIdRoute =
  AuthenticatedAdminEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/listing/$id': typeof ListingIdRoute
  '/admin/generator': typeof AuthenticatedAdminGeneratorRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/listing/$id': typeof ListingIdRoute
  '/admin/generator': typeof AuthenticatedAdminGeneratorRoute
  '/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/admin/new': typeof AuthenticatedAdminNewRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/listing/$id': typeof ListingIdRoute
  '/_authenticated/admin/generator': typeof AuthenticatedAdminGeneratorRoute
  '/_authenticated/admin/listings': typeof AuthenticatedAdminListingsRoute
  '/_authenticated/admin/new': typeof AuthenticatedAdminNewRoute
  '/_authenticated/admin/revenue': typeof AuthenticatedAdminRevenueRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/edit/$id': typeof AuthenticatedAdminEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/listing/$id'
    | '/admin/generator'
    | '/admin/listings'
    | '/admin/new'
    | '/admin/revenue'
    | '/admin/'
    | '/admin/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/listing/$id'
    | '/admin/generator'
    | '/admin/listings'
    | '/admin/new'
    | '/admin/revenue'
    | '/admin'
    | '/admin/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/listing/$id'
    | '/_authenticated/admin/generator'
    | '/_authenticated/admin/listings'
    | '/_authenticated/admin/new'
    | '/_authenticated/admin/revenue'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ListingIdRoute: typeof ListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/revenue': {
      id: '/_authenticated/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AuthenticatedAdminRevenueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new': {
      id: '/_authenticated/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AuthenticatedAdminNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/listings': {
      id: '/_authenticated/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AuthenticatedAdminListingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/generator': {
      id: '/_authenticated/admin/generator'
      path: '/generator'
      fullPath: '/admin/generator'
      preLoaderRoute: typeof AuthenticatedAdminGeneratorRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/edit/$id': {
      id: '/_authenticated/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AuthenticatedAdminEditIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminGeneratorRoute: typeof AuthenticatedAdminGeneratorRoute
  AuthenticatedAdminListingsRoute: typeof AuthenticatedAdminListingsRoute
  AuthenticatedAdminNewRoute: typeof AuthenticatedAdminNewRoute
  AuthenticatedAdminRevenueRoute: typeof AuthenticatedAdminRevenueRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEditIdRoute: typeof AuthenticatedAdminEditIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminGeneratorRoute: AuthenticatedAdminGeneratorRoute,
  AuthenticatedAdminListingsRoute: AuthenticatedAdminListingsRoute,
  AuthenticatedAdminNewRoute: AuthenticatedAdminNewRoute,
  AuthenticatedAdminRevenueRoute: AuthenticatedAdminRevenueRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminEditIdRoute: AuthenticatedAdminEditIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ListingIdRoute: ListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
